"""A 200 that carries canned text but no usage was not generated by the
model; the transport retries it once and logs what the router said."""

import asyncio
import logging

from app.services import ai as ai_service


def _reply(text: str, tokens: int, tool_calls: list | None = None) -> dict:
    message = {"role": "assistant", "content": text}
    if tool_calls:
        message["tool_calls"] = tool_calls
    return {
        "id": "gen-1", "provider": "OpenAI",
        "choices": [{"finish_reason": "stop", "native_finish_reason": "stop", "message": message}],
        "usage": {"prompt_tokens": tokens, "completion_tokens": tokens},
    }


def test_synthetic_reply_is_the_canned_text_without_usage():
    assert ai_service.is_synthetic_reply(_reply("I'm sorry, but I cannot assist with that request.", 0))
    assert not ai_service.is_synthetic_reply(_reply("Claro, con gusto.", 12))
    assert not ai_service.is_synthetic_reply(_reply("", 0))
    assert not ai_service.is_synthetic_reply(_reply("", 0, [{"type": "function", "function": {"name": "x", "arguments": "{}"}}]))
    assert not ai_service.is_synthetic_reply({"choices": []})


def test_transport_retries_once_and_logs(monkeypatch, caplog):
    answers = [_reply("I'm sorry, but I cannot assist with that request.", 0), _reply("Perfecto, el martes a las 5 está libre.", 40)]
    calls: list[dict] = []

    async def fake_post(url, headers, payload, sampling):
        calls.append(payload)
        return answers.pop(0)

    monkeypatch.setattr(ai_service, "_post_json", fake_post)
    with caplog.at_level(logging.WARNING, logger="app.services.ai"):
        data = asyncio.run(ai_service.post_completion("https://x/chat/completions", {}, {"model": "m", "messages": []}, {}))
    assert data["choices"][0]["message"]["content"].startswith("Perfecto")
    assert len(calls) == 2 and calls[0] == calls[1]
    assert "Synthetic completion (attempt 1)" in caplog.text and "finish_reason=stop" in caplog.text


def test_a_second_synthetic_reply_is_returned_as_is(monkeypatch):
    canned = _reply("I'm sorry, but I cannot assist with that request.", 0)
    count = {"n": 0}

    async def fake_post(url, headers, payload, sampling):
        count["n"] += 1
        return canned

    monkeypatch.setattr(ai_service, "_post_json", fake_post)
    data = asyncio.run(ai_service.post_completion("https://x/chat/completions", {}, {"model": "m", "messages": []}, {}))
    assert count["n"] == 2 and data is canned
