/** Team operations and reporting copy for native clients. */
const en = {
  title: "Workspace", subtitle: "Your team and its activity", back: "Back", teams: "Teams", reports: "Reports", people: "People", online: "Online", away: "Away", me: "You", changeAvailability: "Change availability", goOnline: "Go online", goAway: "Set away",
  newTeam: "New team", editTeam: "Edit team", noTeams: "No teams yet", noTeamsHint: "Create a team to route conversations to the right people.", noMembers: "No members", defaultTeam: "Default", open: "open", unassigned: "unassigned", teamName: "Team name", description: "Description", strategy: "Assignment strategy", roundRobin: "Round robin", leastBusy: "Least busy", roundRobinHint: "Distribute conversations between available members in turn.", leastBusyHint: "Assign the available member with the fewest open conversations.", channels: "Channels", channelHint: "Choose the channels this team receives automatically.", members: "Members", defaultHint: "Default team for conversations without another routing match.", save: "Save team", cancel: "Cancel", duplicateName: "A team with this name already exists.", saveFailed: "Could not save the team", loadFailed: "Could not load workspace data", retry: "Try again",
  days7: "7 days", days30: "30 days", localTime: "Local days", seconds: "s", minutes: "min", hours: "h", noData: "No data", noActivity: "No activity during this period", allTeams: "All teams", allChannels: "All channels", web: "Web chat",
  started: "Started", resolved: "Resolved", openNow: "Open now", agentsOnline: "People online", inbound: "Customer messages", humanReplies: "Team replies", aiReplies: "Assistant replies", activeContacts: "Active contacts", firstReply: "Average first reply", resolutionTime: "Average resolution time", daily: "Daily activity", channelActivity: "Started by channel", teamActivity: "Operator activity", replies: "Replies", assigned: "Assigned", currentHint: "Open now follows the selected filters. People online covers the whole workspace. Both are current totals; other figures cover the selected period.", averageHint: "Response and resolution times are averages. No data means no qualifying cases in the period.",
};
const es: typeof en = {
  title: "Equipo", subtitle: "Tu equipo y su actividad", back: "Atrás", teams: "Equipos", reports: "Reportes", people: "Personas", online: "En línea", away: "Ausente", me: "Tú", changeAvailability: "Cambiar disponibilidad", goOnline: "Estar en línea", goAway: "Marcar ausente",
  newTeam: "Nuevo equipo", editTeam: "Editar equipo", noTeams: "Todavía no hay equipos", noTeamsHint: "Crea un equipo para dirigir las conversaciones a las personas indicadas.", noMembers: "Sin integrantes", defaultTeam: "Predeterminado", open: "abiertas", unassigned: "sin asignar", teamName: "Nombre del equipo", description: "Descripción", strategy: "Asignación", roundRobin: "Por turnos", leastBusy: "Menor carga", roundRobinHint: "Reparte las conversaciones por turnos entre los integrantes disponibles.", leastBusyHint: "Asigna al integrante disponible con menos conversaciones abiertas.", channels: "Canales", channelHint: "Elige los canales que este equipo recibe automáticamente.", members: "Integrantes", defaultHint: "Equipo predeterminado para conversaciones sin otra regla de asignación.", save: "Guardar equipo", cancel: "Cancelar", duplicateName: "Ya existe un equipo con este nombre.", saveFailed: "No pudimos guardar el equipo", loadFailed: "No pudimos cargar los datos del equipo", retry: "Reintentar",
  days7: "7 días", days30: "30 días", localTime: "Días locales", seconds: "s", minutes: "min", hours: "h", noData: "Sin datos", noActivity: "No hay actividad durante este período", allTeams: "Todos los equipos", allChannels: "Todos los canales", web: "Chat web",
  started: "Iniciadas", resolved: "Resueltas", openNow: "Abiertas ahora", agentsOnline: "Personas en línea", inbound: "Mensajes de clientes", humanReplies: "Respuestas del equipo", aiReplies: "Respuestas del asistente", activeContacts: "Contactos activos", firstReply: "Primera respuesta promedio", resolutionTime: "Resolución promedio", daily: "Actividad diaria", channelActivity: "Iniciadas por canal", teamActivity: "Actividad por persona", replies: "Respuestas", assigned: "Asignadas", currentHint: "Abiertas ahora respeta los filtros. Personas en línea incluye todo el equipo. Ambas son cifras actuales; las demás corresponden al período seleccionado.", averageHint: "Los tiempos de respuesta y resolución son promedios. Sin datos significa que no hay casos aplicables en el período.",
};
export type WorkspaceStrings = typeof en;
export function workspaceStrings(): WorkspaceStrings {
  try {
    const { getLocales } = require("expo-localization") as typeof import("expo-localization");
    return getLocales()[0]?.languageCode === "es" ? es : en;
  } catch { return en; }
}
