"""Add professional messaging accounts, identities, and durable delivery queues."""

from alembic import op
import sqlalchemy as sa

revision = "0035_social_channels"
down_revision = "0034_agent_reply_delay"
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('app_id', sa.String(length=128), nullable=True),
    sa.Column('external_account_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=True),
    sa.Column('username', sa.String(length=180), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_app_secret', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_refresh_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_source', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='disconnected', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('human_agent_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('webhook_verify_token', sa.String(length=64), nullable=False),
    sa.Column('granted_scopes', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'provider', name='uq_social_channels_client_provider')
    )
    op.create_index(op.f('ix_social_channels_agency_id'), 'social_channels', ['agency_id'], unique=False)
    op.create_index(op.f('ix_social_channels_agent_id'), 'social_channels', ['agent_id'], unique=False)
    op.create_index(op.f('ix_social_channels_client_id'), 'social_channels', ['client_id'], unique=False)
    op.create_index('uq_social_channels_account', 'social_channels', ['provider', 'external_account_id'], unique=True, postgresql_where=sa.text("external_account_id <> ''"))
    op.create_table('social_oauth_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('next_url', sa.Text(), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_oauth_states_agency_id'), 'social_oauth_states', ['agency_id'], unique=False)
    op.create_index(op.f('ix_social_oauth_states_client_id'), 'social_oauth_states', ['client_id'], unique=False)
    op.create_index(op.f('ix_social_oauth_states_expires_at'), 'social_oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_social_oauth_states_user_id'), 'social_oauth_states', ['user_id'], unique=False)
    op.create_table('contact_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_account_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'provider', 'external_account_id', 'external_user_id', name='uq_contact_identity')
    )
    op.create_index(op.f('ix_contact_identities_client_id'), 'contact_identities', ['client_id'], unique=False)
    op.create_index(op.f('ix_contact_identities_contact_id'), 'contact_identities', ['contact_id'], unique=False)
    op.create_table('social_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('external_event_id', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'external_event_id', name='uq_social_webhook_event')
    )
    op.create_index(op.f('ix_social_webhook_events_available_at'), 'social_webhook_events', ['available_at'], unique=False)
    op.create_index(op.f('ix_social_webhook_events_channel_id'), 'social_webhook_events', ['channel_id'], unique=False)
    op.create_index(op.f('ix_social_webhook_events_status'), 'social_webhook_events', ['status'], unique=False)
    op.create_table('social_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('external_message_id', sa.String(length=1024), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'part', name='uq_social_outbox_part')
    )
    op.create_index(op.f('ix_social_outbox_available_at'), 'social_outbox', ['available_at'], unique=False)
    op.create_index(op.f('ix_social_outbox_channel_id'), 'social_outbox', ['channel_id'], unique=False)
    op.create_index(op.f('ix_social_outbox_conversation_id'), 'social_outbox', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_social_outbox_external_message_id'), 'social_outbox', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_social_outbox_message_id'), 'social_outbox', ['message_id'], unique=False)
    op.create_index(op.f('ix_social_outbox_status'), 'social_outbox', ['status'], unique=False)
    op.add_column('conversations', sa.Column('social_channel_id', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('social_pending_escalation', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('is_historical', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('messages', 'external_message_id', type_=sa.String(1024), existing_type=sa.String(255))
    op.add_column('social_outbox', sa.Column('receipt_status', sa.String(length=30), nullable=True))
    op.create_index('uq_social_event_processing', 'social_webhook_events', ['channel_id'], unique=True,
                    postgresql_where=sa.text("status = 'processing'"))
    op.add_column('conversations', sa.Column('social_last_inbound_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('social_reply_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('social_reply_claimed_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('social_thread_owned', sa.Boolean(), server_default='true', nullable=False))
    op.create_foreign_key('fk_conversations_social_channel', 'conversations', 'social_channels', ['social_channel_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_conversations_social_chat', 'conversations', ['social_channel_id', 'external_chat_id'], unique=False)
    op.create_index(op.f('ix_conversations_social_reply_due_at'), 'conversations', ['social_reply_due_at'], unique=False)
    op.create_index(op.f('ix_conversations_social_channel_id'), 'conversations', ['social_channel_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("""INSERT INTO contact_identities (id, client_id, contact_id, provider, external_account_id, external_user_id, created_at)
        SELECT id, client_id, id, 'phone', '', phone, created_at FROM contacts WHERE phone IS NOT NULL""")

# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_history_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conversations_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('messages_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_conversations', sa.Integer(), server_default='20', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_history_imports_channel_id'), 'social_history_imports', ['channel_id'], unique=False)
    op.create_index('uq_social_history_active', 'social_history_imports', ['channel_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing')"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # Opaque provider IDs must not be truncated when removing these channels.
    # Keep the compatible widened message ID column on downgrade.
    op.drop_column('messages', 'is_historical')
    op.drop_column('conversations', 'social_pending_escalation')
    op.drop_index("ix_conversations_social_chat", table_name="conversations")
    op.drop_index("ix_conversations_social_channel_id", table_name="conversations")
    op.drop_index("ix_conversations_social_reply_due_at", table_name="conversations")
    op.drop_constraint("fk_conversations_social_channel", "conversations", type_="foreignkey")
    for column in ("social_thread_owned", "social_reply_claimed_until", "social_reply_due_at", "social_last_inbound_at", "social_channel_id"):
        op.drop_column("conversations", column)
    for table in ("social_history_imports", "social_outbox", "social_webhook_events", "contact_identities", "social_oauth_states", "social_channels"):
        op.drop_table(table)
